_wandb:
    value:
        cli_version: 0.24.0
        e:
            2f0bg8b9nsieer1v7prfho5wbri8zvq4:
                codePath: mlops\scripts\data_versioning.py
                codePathLocal: mlops\scripts\data_versioning.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "56680771584"
                        used: "529444864"
                email: ay.bouguessa@esi-sba.dz
                executable: C:\Users\HP\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 9af7bbe9ff7f652e2bdfcefcd5f674e165fc6c50
                    remote: https://github.com/iAhmeed/flavor-alchemist.git
                host: DESKTOP-THJSOFL
                memory:
                    total: "8425529344"
                os: Windows-11-10.0.26200-SP0
                program: D:\The Flavor Alchemist\mlops\scripts\data_versioning.py
                python: CPython 3.13.1
                root: D:\The Flavor Alchemist
                startedAt: "2026-01-25T21:58:14.306059Z"
                writerId: 2f0bg8b9nsieer1v7prfho5wbri8zvq4
        m: []
        python_version: 3.13.1
        t:
            "3":
                - 2
            "4": 3.13.1
            "5": 0.24.0
            "8":
                - 3
            "12": 0.24.0
            "13": windows-amd64
